//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pc
    {
        public int ID { get; set; }
        public string PC_Name { get; set; }
        public string Type { get; set; }
        public string HDD { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string OS { get; set; }
        public string IP { get; set; }
        public string MAC { get; set; }
        public string MAC2 { get; set; }
        public string NV { get; set; }
        public string NVCode { get; set; }
        public string PB { get; set; }
        public string Office_Located { get; set; }
        public string ServiceTag { get; set; }
        public bool Active { get; set; }
    }
}
